### PR TITLE
docs: add community links

### LINKED ISSUE #6: Add Sign-in with Stacks to next.js template
At least add a comment to study https://github.com/pradel/stacks-next-auth-example to get sign-in with stacks onto  the server.

### PR DESCRIPTION
**Pull request by janniks**
Add [`Ecosystem`](https://github.com/hirosystems/stacks.js-starters/tree/add-community-section#-ecosystem) section to show off community starter projects in README

- closes https://github.com/hirosystems/stacks.js-starters/issues/6

### CODE REVIEW

**Comment by janniks** [comment]
@chrisbward should we add https://github.com/chrisbward/Stacks-Hello-World-Tutorial to the list as well?

**Comment by friedger** [comment]
What is "community" here? Individual developers like @janniks and @pradel or entities like Hiro and Sigle? As we talked about communication yesterday, the separation of we (Hiro) and they (community) could put off.

**Comment by janniks** [comment]
🤔 Good point! It should definitely be welcoming

Does "ecosystem" sound better and we let the maintainers decide if they want to be listed as company/individual (I would have just used whatever the GitHub org/user is)? Or even more generic "similar great resources". Or is any separation of lists too much in your opinion?

**Comment by friedger** [comment]
Two lists sounds fair for me.

**Comment by maryjames77686** [comment]
Hello

**Comment by maryjames77686** [comment]
Hi

**Comment by janniks** [comment]
Changed `Community` to `Ecosystem` and restructured the order to move up the Ecosystem list. Also added emojis to make it feel more friendly and highlight the Ecosystem list

@pradel is that okay for you?

**Comment by pradel** [comment]
@janniks yes !

**Pull request merged**
